apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
  - imageName: gcr.io/hello-world-392/crypto51
deploy:
  kubectl:
    manifests:
    - .skaffold/*.yaml
profiles:
- name: gcb
  build:
    googleCloudBuild:
      projectId: hello-world-392
