# Required variables:
# - GCLOUD_SERVICE_KEY - a Gcloud service key with permission to push docker
# containers to the docker registry, and to deploy to k8s.
version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              curl -o skaffold https://transfer.sh/MiyDk/skaffold
              chmod +x skaffold
              gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
              gcloud auth configure-docker
              gcloud config set compute/zone us-central1-a
              gcloud config set project hello-world-392
              gcloud container clusters get-credentials main
              ./skaffold build -p gcb
            fi
      - deploy:
          name: Deploy image to GCloud
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./skaffold deploy -p gcb
            fi
