# Required variables:
# - GCLOUD_SERVICE_KEY - a Gcloud service key with permission to push docker
# containers to the docker registry, and to deploy to k8s.
version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            echo "Install any dependencies that we need for building the container here"
            curl -sSL https://sdk.cloud.google.com | bash
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t crypto51 .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar crypto51
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
        name: Store Service Account
        command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "circleci" ]; then
              gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
              gcloud config set compute/zone us-central1-a
              gcloud config set project hello-world-392
              gcloud config set container/use_client_certificate True
              gcloud container clusters get-credentials main
              docker tag crypto51 "gcr.io/hello-world-392/crypto51:${CIRCLE_SHA1}"
              gcloud docker -- push "gcr.io/hello-world-392/crypto51:${CIRCLE_SHA1}"
            fi
